spring.application.name=family-fantasy-api

spring.profiles.active=local

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/family_fantasy_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# Hibernate JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
