package family.fantasy.api.locks;

import family.fantasy.api.core.Group;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import java.util.Arrays;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class GroupEntryServiceTest {

    @Mock
    private GroupEntryRepository groupEntryRepository;

    @InjectMocks
    private GroupEntryService groupEntryService;

    /**
     * Tests that a user's pick entry is properly wrapped in a GroupEntry 
     * relationship object and saved to link them to the family league.
     */
    @Test
    void enterGroup_ValidInputs_SavesGroupEntry() {
        Group mockGroup = new Group("Family Group");
        PickEntry mockEntry = new PickEntry();
        
        groupEntryService.enterGroup(mockGroup, mockEntry);

        verify(groupEntryRepository, times(1)).save(any(GroupEntry.class));
    }

    /**
     * Tests that the service correctly retrieves and passes through the sorted 
     * leaderboard data generated by the underlying repository.
     */
    @Test
    void getGroupLeaderboard_ReturnsSortedList() {
        GroupEntry firstPlace = new GroupEntry();
        GroupEntry secondPlace = new GroupEntry();
        List<GroupEntry> mockLeaderboard = Arrays.asList(firstPlace, secondPlace);
        
        when(groupEntryRepository.findByGroupIdOrderByPickEntryTotalScoreDesc(1L))
            .thenReturn(mockLeaderboard);

        List<GroupEntry> result = groupEntryService.getGroupLeaderboard(1L);

        assertEquals(2, result.size());
        verify(groupEntryRepository, times(1)).findByGroupIdOrderByPickEntryTotalScoreDesc(1L);
    }
}